# Generated by Django 3.0.2 on 2020-11-04 03:51

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensor', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffstreetParkingSpaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=20, null=True)),
                ('streetName', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('zone', models.CharField(max_length=50, null=True)),
                ('count', models.BigIntegerField(null=True)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Offstreet Spaces',
            },
        ),
        migrations.CreateModel(
            name='OnstreetParkingSpaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=20, null=True)),
                ('streetName', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('zone', models.CharField(max_length=50, null=True)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('sensor_status', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='sensor.Sensor')),
            ],
            options={
                'verbose_name_plural': 'Onstreet Spaces',
            },
        ),
        migrations.CreateModel(
            name='OnstreetParkingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('vehicle_type', models.CharField(max_length=20)),
                ('vehicle_registration_number', models.CharField(max_length=10)),
                ('time_of_parking', models.DateTimeField(auto_now_add=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('mpesaTransaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.MpesaPayments')),
                ('parkingSpace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onstreetpaymentInfo', to='parking.OnstreetParkingSpaces')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onstreetparkingInfo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Onstreet Details',
            },
        ),
        migrations.CreateModel(
            name='OffstreetParkingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('vehicle_type', models.CharField(max_length=20)),
                ('vehicle_registration_number', models.CharField(max_length=10)),
                ('time_of_parking', models.DateTimeField(auto_now_add=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('mpesaTransaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.MpesaPayments')),
                ('parkingSpace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offstreetpaymentInfo', to='parking.OffstreetParkingSpaces')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offstreetparkingInfo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Offstreet Details',
            },
        ),
    ]
