# Generated by Django 3.0.2 on 2020-11-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onstreetparkingspaces',
            name='sensor_status',
        ),
    ]
