# Generated by Django 3.0.2 on 2020-03-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspaces',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
