# Generated by Django 3.0.2 on 2020-03-14 17:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspaces',
            name='id',
        ),
        migrations.AddField(
            model_name='parkingspaces',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='parkingspaces',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='parkingspaces',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='parkingspaces',
            name='owner',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parkingspaces',
            name='parking_space_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkingspaces',
            name='parking_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parkingspaces',
            name='streetName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parkingspaces',
            name='zone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mpesapayments',
            name='PhoneNumber',
            field=models.CharField(max_length=16),
        ),
        migrations.CreateModel(
            name='ParkingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('vehicle_type', models.CharField(max_length=20)),
                ('vehicle_registration_number', models.CharField(max_length=10)),
                ('time_of_parking', models.DateTimeField(auto_now_add=True)),
                ('parkingSpace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkingspace', to='parking.ParkingSpaces')),
                ('payments_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='parking.MpesaPayments')),
            ],
            options={
                'verbose_name_plural': 'Parking Details',
            },
        ),
    ]
