# Generated by Django 3.0.2 on 2020-03-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayments',
            name='PhoneNumber',
            field=models.CharField(max_length=15),
        ),
    ]
