# Generated by Django 3.0.2 on 2020-10-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParkingDetails',
        ),
    ]
