# Generated by Django 3.0.2 on 2020-10-22 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0002_delete_parkingdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('vehicle_type', models.CharField(max_length=20)),
                ('vehicle_registration_number', models.CharField(max_length=10)),
                ('time_of_parking', models.DateTimeField(auto_now_add=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('mpesaTransaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.MpesaPayments')),
                ('parkingSpace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parkingInfo', to='parking.ParkingSpaces')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkingInfo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Parking Details',
            },
        ),
    ]
