# Generated by Django 3.0.2 on 2020-11-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_onstreetparkingspaces_sensor_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offstreetparkingspaces',
            old_name='status',
            new_name='reserved',
        ),
        migrations.RenameField(
            model_name='onstreetparkingspaces',
            old_name='status',
            new_name='reserved',
        ),
    ]
