# Generated by Django 3.0.2 on 2020-03-14 18:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20200314_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpaces',
            fields=[
                ('parking_space_id', models.AutoField(primary_key=True, serialize=False)),
                ('parking_type', models.CharField(max_length=100, null=True)),
                ('owner', models.CharField(max_length=20, null=True)),
                ('streetName', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=False, null=True)),
                ('zone', models.CharField(max_length=50, null=True)),
                ('lat', models.FloatField(null=True)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Parking Spaces',
            },
        ),
        migrations.CreateModel(
            name='ParkingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('vehicle_type', models.CharField(max_length=20)),
                ('vehicle_registration_number', models.CharField(max_length=10)),
                ('time_of_parking', models.DateTimeField(auto_now_add=True)),
                ('parkingSpace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkingspace', to='parking.ParkingSpaces')),
                ('payments_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='parking.MpesaPayments')),
            ],
            options={
                'verbose_name_plural': 'Parking Details',
            },
        ),
    ]
