# Generated by Django 3.0.2 on 2020-11-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_parkingdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParkingSpaces',
            new_name='OnstreetParkingSpaces',
        ),
    ]
