# Generated by Django 3.0.2 on 2020-03-14 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_parkingspaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField()),
                ('vehicle_type', models.CharField(max_length=20)),
                ('vehicle_registration_number', models.CharField(max_length=10)),
                ('time_of_parking', models.DateTimeField(auto_now_add=True)),
                ('parkingSpace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkingspace', to='parking.ParkingSpaces')),
                ('payments_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='parking.MpesaPayments')),
            ],
            options={
                'verbose_name_plural': 'Parking Details',
            },
        ),
    ]
