# Generated by Django 3.0.2 on 2020-11-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_auto_20201101_2007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OnstreetParkingSpaces',
            new_name='ParkingSpaces',
        ),
    ]
