# Generated by Django 3.0.2 on 2020-11-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_auto_20201108_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='offstreetparkingspaces',
            name='disabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='onstreetparkingspaces',
            name='disabled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
