# Generated by Django 3.0.2 on 2020-11-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20201101_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onstreetparkingspaces',
            options={'verbose_name_plural': 'Onstreet Spaces'},
        ),
        migrations.RenameField(
            model_name='onstreetparkingspaces',
            old_name='active',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='onstreetparkingspaces',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='onstreetparkingspaces',
            name='lng',
        ),
        migrations.RemoveField(
            model_name='onstreetparkingspaces',
            name='parking_type',
        ),
    ]
