# Generated by Django 3.0.2 on 2020-11-01 17:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0007_auto_20201101_2024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParkingDetails',
            new_name='OnstreetParkingDetails',
        ),
    ]
