# Generated by Django 3.0.2 on 2020-11-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_auto_20201101_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onstreetparkingdetails',
            name='parkingSpace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onstreetpaymentInfo', to='parking.OnstreetParkingSpaces'),
        ),
    ]
