# Generated by Django 3.0.2 on 2020-11-01 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_auto_20201101_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offstreetparkingdetails',
            name='parkingSpace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offstreetpaymentInfo', to='parking.OffstreetParkingSpaces'),
        ),
    ]
