# Generated by Django 3.0.2 on 2020-10-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='super_admin'),
        ),
    ]
