# Generated by Django 3.0.2 on 2020-11-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_serial_number', models.CharField(max_length=20, null=True)),
                ('make', models.CharField(max_length=100, null=True)),
                ('detected', models.BooleanField(default=False)),
                ('date_of_manufacture', models.DateField(null=True)),
            ],
        ),
    ]
