export const GET_PARKING = "GET_PARKING";
export const GET_PARKING_DETAILS = "GET_PARKING_DETAILS";
export const SET_USER_LOCATION = "SET_USER_LOCATION";
export const SET_GEOCODED_LOCATION = "SET_GEOCODED_LOCATION";
export const SIGN_IN_USER = "SIGN_IN_USER";
export const SIGN_UP_USER = "SIGN_UP_USER";
export const SIGN_OUT_USER = "SIGN_OUT_USER";
export const LOAD_USER = "LOAD_USER";
export const GET_PAYMENT_INFO = "GET_PAYMENT_INFO"
export const CLEAR_PARKING_INFO = "CLEAR_PARKING_INFO"
export const ADMINISTRATION = "ADMINISTRATION"
export const SENDSMS = "SENDSMS"




